title: "Federico P. de Isidro Gómez"
description: "Curriculum vitae"
remote_theme: sharu725/online-cv

# Sidebar details
sidebar:
  name: "Federico P. de Isidro Gómez"
  tagline: "Researcher | Engineer | Developer"
  avatar: "/assets/images/profile.jpg"  # Make sure this image exists
  email: "your.email@example.com"
  phone: "+1234567890"
  timezone: "Europe/Madrid"
  linkedin: "your-linkedin"
  github: "your-github"
  twitter: "your-twitter"

# Sections on the page
sections:
  - about
  - experience
  - education
  - projects
  - skills
  - contact

# Navigation configuration
header_pages:
  - index.md
  - contact.md
  - publications.md

# Social links
social_links:
  - { icon: "github", link: "https://github.com/fede-pe" }
  - { icon: "linkedin", link: https://www.linkedin.com/in/federicoig" }
  - { icon: "orcid", link: https://orcid.org/0000-0003-2289-2364" }