# Site Settings

title: "TheFedePage"
description: "Curriculum vitae"
remote_theme: sharu725/online-cv
theme_skin: ceramic

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development